language: java
notifications:
  email: false
jdk:
- openjdk11
stages:
- install
- name: deploy
  if: tag =~ /^v\d+\.\d+(\.\d+)?(-\S*)?$/
jobs:
  include:
  - stage: install
    script:
    - mvn --settings=.travis.settings.xml clean install -B -V
  - stage: deploy
    script:
    - echo "Deploy stage.."
branches:
  only:
  - master
  - travis
cache:
  directories:
  - "$HOME/.m2/repository"
